server:
  port: 80

logging:
  level:
    com.*: debug
    org.*: debug
  file:
    path: /home/cloud/out.log

spring:
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML5
    encoding: UTF-8
    cache: false